### ISSUE TITLE
Implement the Type Main design in the libc startup code

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wasi-libc#8]

**Comment by ricochet** [comment]
From what I understood from the presentation today, this issue is for changing main to accept args as `list<string>`, but coded in a way so that we could later adopt Wit interfaces.

I'm interested in seeing a sketch for the later levels of adoption like passing in streams. I'm also curious if we expect to be able to pass in complex types like records or even streams of records.

**Comment by kulakowski-wasm** [comment]
This issue tracked an experimental idea of how to implement the Command world. We've decided to try something slightly different that makes typed main no longer special.
